### PR TITLE
upgrade Ben.Demystifier to 0.1.3

### PR DESCRIPTION
**Pull request by vip32**
refers to issue #9

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR! I'll take a look at this again 👍

**Comment by vip32** [comment]
Hi @nblumhardt, can you please merge this PR?

**Comment by nblumhardt** [comment]
Hi @vip32 - sorry about the delay.

I'm happy with updating the dependency version, but I don't want to mark this package 1.0, it's essentially dead on the vine thanks to the improvements now in .NET Core, so marking it as "supported" via a 1.0 moniker seems like the wrong signal to send.

Looking at https://github.com/benaadams/Ben.Demystifier/issues - it doesn't seem like Ben is pushing hard for a 1.0 either, and I'd guess for similar reasons.

Given the amount of code here is so small, if it's blocking you from marking another package as 1.0, perhaps copying https://github.com/nblumhardt/serilog-enrichers-demystify/blob/dev/src/Serilog.Enrichers.Demystify/Enrichers/Demystify/DemystifiedStackTraceEnricher.cs into your own project would be a good workaround, in this case?

Thanks for sending the PR, though - much appreciated - and sorry to hold up the works! :-)

Best regards,
Nick

**Comment by nblumhardt** [comment]
Ah I see my mistake, this is setting the `VersionPrefix` which will still generate pre-release packages from `dev`. I'll try pushing this through and see if the build still works, but I suspect this project will be archived sometime soon. Thanks!

**Pull request merged**
